homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('resume/', views.resume, name='resume'),
    path('contact/', views.contact, name='contact'),
    path('schedule/', views.schedule, name='schedule'),
    path("delete/<int:id>", views.delete_schedule, name="delete_schedule")
]

ppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.
class Schedule(models.Model):
    title = models.CharField(max_length=100)
    location = models.CharField(max_length=200)
    categories = models.CharField(max_length=100)
    date = models.DateField(null=True)
    time = models.TimeField(null=True)
    day = models.CharField(max_length=100)

homepage/views.py
from django.shortcuts import render, redirect
import datetime
from . import form, models

# Create your views here.
def home(request):
    return render(request, 'story3_home.html')

def about(request):
    return render(request, 'story3_about.html')

def resume(request):
    return render(request, 'story3_resume.html')

def contact(request):
    return render(request, 'story3_contact.html')

def schedule(request):
    if(request.method == "POST"):
        forms = form.ScheduleForm(request.POST)
        if(forms.is_valid()):
            schedule = models.Schedule(title=request.POST['title'],
                                        location=request.POST['location'],
                                        date="{}-{:02d}-{:02d}".format(request.POST['date_year'],int(request.POST['date_month']),int(request.POST['date_day'])),
                                        categories=request.POST['categories'],
                                        time=request.POST['time'],
                                        day=request.POST['day']
                                        )
            schedule.save()
            return redirect('/schedule')
        else:
            list_schedule = models.Schedule.objects.all().order_by('date').order_by('time')
            return render(request, 'story3_schedule.html', {'forms':forms, 'schedules':list_schedule, "length":len(list_schedule)})
    else:
        forms = form.ScheduleForm()
        list_schedule = models.Schedule.objects.all().order_by('date').order_by('time')
        return render(request, 'story3_schedule.html', {'forms':forms, 'schedules':list_schedule, "length":len(list_schedule)})

def delete_schedule(request,id):
    if(request.method == "POST"):
        schedule = models.Schedule.objects.get(id=id)
        schedule.delete()
        return redirect('/schedule')

homepage/templates/story3_about.html
<!DOCTYPE html>
{% load static %}
<html lang='en'>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>My Personal Website</title>
    <link rel="stylesheet" href="{% static 'css/bs/bootstrap.min.css' %}">
    <link rel='stylesheet' href="{% static 'css/story3.css' %}"/>
  </head>
  <body>
      <div class = "header">
        <a href = "{% url 'homepage:home' %}"><img class = "img" src = "{% static 'images/icons8-c-letter-104.png' %}"></a>
        <a href = "{% url 'homepage:home' %}"><button class = "btn home">Home</button></a>
        <a href = "{% url 'homepage:about' %}"><button class = "btn about">About</button></a>
        <a href = "{% url 'homepage:resume' %}"><button class = "btn resume">Resume</button></a>
        <a href = "{% url 'homepage:contact' %}"><button class = "btn contact">Contact</button></a>
        <a href = "{% url 'homepage:schedule' %}"><button class = "btn schedule">Schedule</button></a>
      </div>

      <div class="middle_about">
        <div class="row">
          <div class="col-lg-4">
              <b>About Me</b><br>
              Hi, my name is Carlo Tupa Indriauan.
              I am currently pursuing computer science bachelor’s degree at Universitas Indonesia.
              I am still new to web developing so it’s still much for me to learn.
          </div>
          <div class="col-lg-4">
              <img class = "img_1" src="{% static 'images/p1.jpg' %}">
          </div>
          <div class="col-lg-4">
              <b>Details</b><br>
              Name        : Carlo Tupa Indriauan<br>
              Birth Date  : November, 25th 2000<br>
              Location    : Depok, Indonesia<br>
          </div>
        </div>
      </div>

      <div class="contact">
        <div class="row">
          <div class="fixed-bottom">
            <div class="icon">
              <a href="https://www.instagram.com/ctupa7/" target="_blank">
                <img src= "{% static 'images/icons8-instagram-64.png' %}", alt="Instagram"></a>
              <a href="https://www.linkedin.com/in/carlo-silalahi/" target="_blank">
                <img src="{% static 'images/icons8-linkedin-48.png' %}", alt="Linkedin"></a>
              <a href="mailto:ctupa7@gmail.com" target="_blank">
                <img src="{% static 'images/icons8-gmail-48.png' %}", alt="Gmail"></a>
            </div>
          </div>
        </div>
      </div>
  </body>
</html>

homepage/templates/story3_contact.html
<!DOCTYPE html>
{% load static %}
<html lang='en'>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Personal Website</title>
    <link rel="stylesheet" href="{% static 'css/bs/bootstrap.min.css' %}">
    <link rel='stylesheet' href="{% static 'css/story3.css' %}"/>
  </head>
  <body>
      <div class = 'header'>
        <a href = "{% url 'homepage:home' %}"><img class = "img" src = "{% static 'images/icons8-c-letter-104.png' %}"></a>
        <a href = "{% url 'homepage:home' %}"><button class = "btn home">Home</button></a>
        <a href = "{% url 'homepage:about' %}"><button class = "btn about">About</button></a>
        <a href = "{% url 'homepage:resume' %}"><button class = "btn resume">Resume</button></a>
        <a href = "{% url 'homepage:contact' %}"><button class = "btn contact">Contact</button></a>
        <a href = "{% url 'homepage:schedule' %}"><button class = "btn schedule">Schedule</button></a>
      </div>

      <div class = 'middle_contact'>
        <h2>Connect With Me Today</h2>
        <div class = box>
            <div class = small_box>
                <p>Feel free to ask me anything.</p>
            </div>
            <div class = big_box>
            </div>
        </div>
      </div>

      <div class="contact">
          <div class="row">
            <div class="fixed-bottom">
              <div class="icon">
                <a href="https://www.instagram.com/ctupa7/" target="_blank">
                  <img src="{% static 'images/icons8-instagram-64.png' %}", alt="Instagram"></a>
                <a href="https://www.linkedin.com/in/carlo-silalahi/" target="_blank">
                  <img src="{% static 'images/icons8-linkedin-48.png' %}", alt="Linkedin"></a>
                <a href="mailto:ctupa7@gmail.com" target="_blank">
                  <img src="{% static 'images/icons8-gmail-48.png' %}", alt="Gmail"></a>
              </div>
            </div>
          </div>
      </div>
  </body>
</html>

homepage/templates/story3_home.html
<!DOCTYPE html>
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Personal Website</title>
    <link rel="stylesheet" href="{% static 'css/bs/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/story3.css' %}"/>
  </head>
  <body>
      <div class = "header">
        <a href = "{% url 'homepage:home' %}"><img class = "img" src = "{% static 'images/icons8-c-letter-104.png' %}"></a>
        <a href = "{% url 'homepage:home' %}"><button class = "btn home">Home</button></a>
        <a href = "{% url 'homepage:about' %}"><button class = "btn about">About</button></a>
        <a href = "{% url 'homepage:resume' %}"><button class = "btn resume">Resume</button></a>
        <a href = "{% url 'homepage:contact' %}"><button class = "btn contact">Contact</button></a>
        <a href = "{% url 'homepage:schedule' %}"><button class = "btn schedule">Schedule</button></a>
      </div>

      <div class = "middle_home">
        <h1>I'm Carlo</h1>
        <h4>a novice web developer</h4>
      </div>
      
      <div class="contact">
        <div class="row">
          <div class="fixed-bottom">
            <div class="icon">
              <a href="https://www.instagram.com/ctupa7/" target="_blank">
                <img src="{% static 'images/icons8-instagram-64.png' %}", alt="Instagram"></a>
              <a href="https://www.linkedin.com/in/carlo-silalahi/" target="_blank">
                <img src="{% static 'images/icons8-linkedin-48.png' %}", alt="Linkedin"></a>
              <a href="mailto:ctupa7@gmail.com" target="_blank">
                <img src="{% static 'images/icons8-gmail-48.png' %}", alt="Gmail"></a>
            </div>
          </div>
        </div>
      </div>
  </body>
</html>

homepage/templates/story3_resume.html
<!DOCTYPE html>
{% load static %}
<html lang='en'>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Personal Website</title>
    <link rel="stylesheet" href="{% static 'css/bs/bootstrap.min.css' %}">
    <link rel='stylesheet' href="{% static 'css/story3.css' %}"/>
  </head>
  <body>
      <div class = 'header'>
          <a href = "{% url 'homepage:home' %}"><img class = "img" src = "{% static 'images/icons8-c-letter-104.png' %}"></a>
          <a href = "{% url 'homepage:home' %}"><button class = "btn home">Home</button></a>
          <a href = "{% url 'homepage:about' %}"><button class = "btn about">About</button></a>
          <a href = "{% url 'homepage:resume' %}"><button class = "btn resume">Resume</button></a>
          <a href = "{% url 'homepage:contact' %}"><button class = "btn contact">Contact</button></a>
          <a href = "{% url 'homepage:schedule' %}"><button class = "btn schedule">Schedule</button></a>
      </div>

      <div class="middle_resume">
            <div class="row">
              <div class="col-lg-4">
                  <p><b>SKILLS</b><br>Python<br>Java<br>HTML(5)<br>CSS(3)<br>Javascript<br>Django</p>
              </div>
              <div class="col-lg-4">
                  <b>WORK EXPERIENCES</b><br>404 Not Found<br>Maybe you'll be the first lucky one :).<br>
                  <a href = "{% url 'homepage:contact' %}"><button class = "bttn">HIRE ME TODAY</button></a>
              </div>
              <div class="col-lg-4">
                    <b>Bachelor's Degree</b><br>
                    August 2018 - Present<br>
                    Universitas Indonesia<br>
                    Currently pursuing computer science bachelor’s degree at 3rd Semester.<br>
                    <br>
                    <b>High School Diploma</b><br>
                    July 2015 - May 2018<br>
                    SMAN 8 Pekanbaru<br>
                    I graduated from SMAN 8 Pekanbaru, where I enjoyed doing math and met lot of friends.
              </div>
            </div>
          </div>

      <div class="contact">
            <div class="row">
              <div class="fixed-bottom">
                <div class="icon">
                  <a href="https://www.instagram.com/ctupa7/" target="_blank">
                    <img src="{% static 'images/icons8-instagram-64.png' %}", alt="Instagram"></a>
                  <a href="https://www.linkedin.com/in/carlo-silalahi/" target="_blank">
                    <img src="{% static 'images/icons8-linkedin-48.png' %}", alt="Linkedin"></a>
                  <a href="mailto:ctupa7@gmail.com" target="_blank">
                    <img src="{% static 'images/icons8-gmail-48.png' %}", alt="Gmail"></a>
                </div>
              </div>
            </div>
        </div>
  </body>
</html>

homepage/templates/story3_schedule.html
<!DOCTYPE html>
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Personal Website</title>
    <link rel="stylesheet" href="{% static 'css/bs/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/story3.css' %}"/>
  </head>
  <body>
      <div class = "header">
        <a href = "{% url 'homepage:home' %}"><img class = "img" src = "{% static 'images/icons8-c-letter-104.png' %}"></a>
        <a href = "{% url 'homepage:home' %}"><button class = "btn home">Home</button></a>
        <a href = "{% url 'homepage:about' %}"><button class = "btn about">About</button></a>
        <a href = "{% url 'homepage:resume' %}"><button class = "btn resume">Resume</button></a>
        <a href = "{% url 'homepage:contact' %}"><button class = "btn contact">Contact</button></a>
        <a href = "{% url 'homepage:schedule' %}"><button class = "btn schedule">Schedule</button></a>
      </div>

      <div id="schedule" class="container part" style="padding-top: 90px; margin-top: 0px; margin-bottom: 0px;">
        <h1 class="text-center bold">My Schedule</h1>
        <div class="row justify-content-center mt-3">
            <div class="col-3">
                <form action="{% url 'homepage:schedule' %}" method="post">
                    {% csrf_token %}
                    {% for field in forms %}
                    <div class="form-group" style="margin-right: 0; margin-bottom: 10px; font-size: 1rem">
                        <label for="id_{{ field.label.lower }}">{{ field.label }}</label>
                        {{ field.errors }}
                        {{ field }}
                    </div>
                    {% endfor %}
                    <button type="submit" class="btn-secondary">Submit</button>
                </form>
            </div>
            <div class="col-5 offset-sm-1">
                {% if length == 0 %}
                    <h3 class="text-center">No Schedule</h3>
                {% endif %}
                <div class="row" style="overflow: auto; height: 28rem">
                {% for i in schedules %}
                    <div class="col-8 mb-3" style="border: #3c3c3c solid;  height: 13rem; border-radius: 10px;">
                        <h4 class="bold">{{ i.title }}</h4>
                        <h5>Location :
                            <span class="semibold">{{ i.location }}</span></h5>
                        <h5 class="bold">{{ i.day }}</h5>
                        <h5>{{ i.date }} {{ i.time }}</h5>
                        <h6 class="bold text-right">{{ i.categories }}</h6>
                        <form action="{% url 'homepage:delete_schedule' id=i.id %}" method="post">
                        {% csrf_token %}
                            <button type="submit" class="btn-danger">Delete</button>
                        </form>
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <script>
        let monthDOM = document.getElementById("id_date_month");
        let dayDOM = document.getElementById("id_date_day");
        let yearDOM = document.getElementById("id_date_year");
        let dayFormDOM = document.getElementById("id_day");

        let dayList =[
            "Sunday",
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday"
        ]

        let dateDetail = {
            month: monthDOM.value,
            day:dayDOM.value,
            year:yearDOM.value
        }

        let strDate = dateDetail.year+" "+dateDetail.month+"-"+dateDetail.day;
        let date = new Date(strDate);
        dayFormDOM.value = dayList[date.getDay()];

        monthDOM.onchange = (el) => {
            dateDetail.month = el.target.value;
            strDate = dateDetail.year+"-"+dateDetail.month+"-"+dateDetail.day;
            date = new Date(strDate);
            dayFormDOM.value = dayList[date.getDay()];

        }
        dayDOM.onchange = (el) => {
            dateDetail.day = el.target.value;
            strDate = dateDetail.year+"-"+dateDetail.month+"-"+dateDetail.day;
            date = new Date(strDate);
            dayFormDOM.value = dayList[date.getDay()];
        }
        yearDOM.onchange = (el) => {
            dateDetail.year = el.target.value;
            strDate = dateDetail.year+"-"+dateDetail.month+"-"+dateDetail.day;
            date = new Date(strDate);
            dayFormDOM.value = dayList[date.getDay()];
        }
    </script>

      
      <!-- <div class="contact">
        <div class="row">
          <div class="fixed-bottom">
            <div class="icon">
              <a href="https://www.instagram.com/ctupa7/" target="_blank">
                <img src="{% static 'images/icons8-instagram-64.png' %}", alt="Instagram"></a>
              <a href="https://www.linkedin.com/in/carlo-silalahi/" target="_blank">
                <img src="{% static 'images/icons8-linkedin-48.png' %}", alt="Linkedin"></a>
              <a href="mailto:ctupa7@gmail.com" target="_blank">
                <img src="{% static 'images/icons8-gmail-48.png' %}", alt="Gmail"></a>
            </div>
          </div>
        </div>
      </div> -->
  </body>
</html>